# Meta

env:           "production"
docs_file:     "bulma-docs.min"

# Build

markdown:      kramdown
permalink:     pretty
url:           https://docs.rubyist.cn/bulma
exclude:       ['icons', 'node_modules', 'templates', '.babelrc', 'bulma-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock']
